version: '3'
services:

  install-api1:
    image: mobjack/brackets:install-api
    hostname: ingest-api1
    build: ./services/install-api/
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    ports:
        - '8800:80'
    volumes:
        - ./services/ingest-api:/app


networks:
  default:
    external:
      name: bracket_install

